/// Flutter icons Indicator
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Indicator
///      fonts:
///       - asset: fonts/Indicator.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Indicator {
  Indicator._();

  static const _kFontFam = 'Indicator';
  static const String? _kFontPkg = null;

  static const IconData image2vector__1_ = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
