/// Flutter icons Warning
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Warning
///      fonts:
///       - asset: fonts/Warning.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Warning {
  Warning._();

  static const _kFontFam = 'Warning';
  static const String? _kFontPkg = null;

  static const IconData image2vector2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector3 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
